"""Add image_path field to Exercise model

Revision ID: a9594b6e780f
Revises: bea5beddbe99
Create Date: 2025-08-06 00:25:01.672273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9594b6e780f'
down_revision = 'bea5beddbe99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
