"""Add subject field to Exercise model

Revision ID: bea5beddbe99
Revises: cb3da7a6e921
Create Date: 2025-08-05 15:27:04.071784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea5beddbe99'
down_revision = 'cb3da7a6e921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
